### PR TITLE
WIP: initial adding of masternode pay info to getblocktemplate

### PR DESCRIPTION
**Pull request by 0x6b656e**
Needs to be changed to populate correct values

### CODE REVIEW

**Comment by 0x6b656e** [comment]
reference https://github.com/s-nomp/node-stratum-pool/blob/ad166d2cd1b5f7d59d53e170878b85e6ea9c6ed7/lib/blockTemplate.js#L39

and 

https://github.com/s-nomp/node-stratum-pool/blob/master/lib/transactions.js#L221

**Comment by 0x6b656e** [comment]
Once adding these to the getblocktemplate RPC they will be returned for the stratum module to grab the info from to use in constructing the tx outputs

**Comment by 0x6b656e** [comment]
Other reference for values https://github.com/Snowgem/Snowgem/blob/e0d3478a983c0927c9a6a5d934df0c725b5038dc/src/rpcmining.cpp#L748

**Comment by 0x6b656e** [comment]
if these items _masternodeReward, masternodePayee ,  masternodePayment _ return the correct values from _rpcData.payee_amount, rpcData.payee, rpcData.masternode_payments _ 

the stratum will pick them up and no further modification is needed to construct the transactions that need a masternode payment

**Comment by 48thRonin** [comment]
See https://github.com/anonymousbitcoin/anon/tree/MN-stratum-fix

**Pull request closed without merging**
